name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username from Docker Hub aucthentication"
      DOCKERHUB_TOKEN:
        required: true
        description: "Password from Docker Hub aucthentication"

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Python flake8
        run: docker compose run --rm app sh -c "flake8"
  
  terraform:
    name: Terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform lint
        run: |
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init -backedn=false
          docker compose run --rm terraform -chdir=setup/ init -backend=false
          docker compose run --rm terraform -chdir=deploy/ validate
          docker compose run --rm terraform -chdir=setup/ validate
          docker compose run --rm terraform -chdir=deploy/ fmt -check
          docker compose run --rm terraform -chdir=setup/ fmt -check
          
